export const WEB_SIDER_WIDTH = 250;
export const WEB_SIDER_COLLAPSED_WIDTH = 42;
export const WEB_SIDER_HORIZONTAL_PADDING = 25;
export const WEB_SIDER_COLLAPSED_HORIZONTAL_PADDING = 15;
export const WEB_SIDER_ITEM_ICON_SIZE = 24;
